export const icons = {
  back: require("./back.png"),
  forward: require("./forward.png"),
  bullet: require("./bullet.png"),
  bug: require("./ladybug.png"),
  eyeOpen: require("./open-eye.png"),
  eyeClose: require("./close-eye.png"),
  scan: require("./scan.png"),
  bell: require("./bell.png"),
  receive: require("./receive.png"),
  swap: require("./swap.png"),
  send: require("./send.png"),
  buysell: require("./buysell.png"),
  plus: require("./plus.png"),
  times: require("./times.png"),
  check: require("./check.png"),
  icon: require("./icon.png"),
  mika: require("./mika.png"),
  transfer: require("./transfer.png"),
  credit: require("./credit.png"),
  sent: require("./sent.png"),
  qr: require("./qr.png"),
  lock: require("./lock.png"),
  person: require("./person.png"),
  clipboard: require("./clipboard.png"),
  face: require("./face.png"),

  // coins
  usa: require("./usa.png"),
  btc: require("./btc.png"),
  doge: require("./doge.png"),
  etherum: require("./etherum.png"),
  tron: require("./tron.png"),
  monero: require("./monero.png"),
  theta: require("./theta.png"),
  ltc: require("./ltc.png"),
  bcash: require("./bcash.png"),
  greenChart: require("./green-chart.png"),
  redChart: require("./red-chart.png"),

  currency: require("./currency.png"),
  wallet: require("./wallet.png"),
  transaction: require("./transaction.png"),
  security: require("./security.png"),
  community: require("./community.png"),
  delete: require("./delete.png"),
  help: require("./help.png"),
  logout: require("./logout.png"),
  search: require("./search.png"),
  google: require("./google.png"),
  shirt: require("./shirt.png"),
  bg: require("./bg.png"),
  percent: require("./percent.png"),
  van: require("./van.png"),
  chart: require("./chart.png"),
  calendar: require("./calendar.png"),
  cube: require("./cube.png"),
  details: require("./details.png"),
  phone: require("./phone.png"),
  password: require("./password.png"),
  social: require("./social.png"),
  creditCard: require("./credit-card.png"),
  arrowRight: require("./arrow-long-right.png"),

  // communities
  facebook: require("./facebook.png"),
  instagram: require("./instagram.png"),
  telegram: require("./telegram.png"),
  twitter: require("./twitter.png"),
  redTimes: require("./red-times.png"),
  greenCheck: require("./check-circle.png"),
  // reddit: require("./reddit.png"),
  // youtube: require("./youtube.png"),

  // active tab icons
  activeBarChart: require("./active/product.png"),
  activeLearn: require("./active/learn.png"),
  activemarket: require("./active/dashboard.png"),
  activewallet: require("./active/wallet.png"),
  activesettings: require("./inactive/profile.png"),
  // Inactive tab icons
  inactiveBarChart: require("./inactive/product.png"),
  inactiveLearn: require("./inactive/learn.png"),
  inactivemarket: require("./inactive/dashboard.png"),
  inactivewallet: require("./inactive/wallet.png"),
  inactivesettings: require("./inactive/profile.png"),

  // flags
  ngn: require("./ngn.png"),
  gbp: require("./gbp.png"),
};

export type IconTypes = keyof typeof icons;
